[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[main]]
    identifier = "recipe"
    name = "Recipes"
    url = "/recipe/"
    weight = 20

[[main]]
    identifier = "blog"
    name = "Writing"
    url = "/blog/"
    weight = 20
