description = "My name is Masami and I'm a home cook sharing recipes and cooking inspiration. I'm a farmers market and local food enthusiast. Cook with me!"
landingImg = "https://storage.googleapis.com/masamicooksimages/22C99696-B94B-47FF-9D04-DAF77B11DBDB.jpg"
mainSections = ["blog","recipe"]

[comment]
    # Options: disqus and commento.
    platform = ""

    [comment.disqus]
        shortname = ""

    [comment.commento]
        # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty. 
        url = "https://www.masamicooks.com"
