baseURL = "https://www.masamicooks.com"
languageCode = "en-us"
title = "MasamiCooks"
theme = "eureka"
googleAnalytics = "UA-172414905-1"
copyright = "©2020 Masami Cookson"
[taxonomies]
  tag = "tags"
  category = "categories"
  style = "styles"
